-- Transactions table
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date DATE NOT NULL,
  description TEXT NOT NULL,
  amount FLOAT8 NOT NULL,
  type TEXT NOT NULL,
  category TEXT,
  subcategory TEXT,
  confidence FLOAT8 DEFAULT 0,
  needs_review BOOLEAN DEFAULT FALSE,
  imported_from TEXT,
  imported_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category);

-- Goals table
CREATE TABLE IF NOT EXISTS goals (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  type TEXT NOT NULL,
  target_amount FLOAT8 NOT NULL,
  current_amount FLOAT8 DEFAULT 0,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  category TEXT,
  recurrence TEXT NOT NULL,
  notify_at_50 BOOLEAN DEFAULT FALSE,
  notify_at_75 BOOLEAN DEFAULT FALSE,
  notify_at_90 BOOLEAN DEFAULT FALSE,
  notify_on_exceed BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'active',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_goals_status ON goals(status);
CREATE INDEX IF NOT EXISTS idx_goals_type ON goals(type);
CREATE INDEX IF NOT EXISTS idx_goals_dates ON goals(start_date, end_date);

-- Insights table
CREATE TABLE IF NOT EXISTS insights (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo TEXT NOT NULL,
  título TEXT NOT NULL,
  descrição TEXT NOT NULL,
  impacto TEXT NOT NULL,
  ação_sugerida TEXT NOT NULL,
  economia_potencial FLOAT8,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  is_applied BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_insights_created_at ON insights(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_insights_tipo ON insights(tipo);
CREATE INDEX IF NOT EXISTS idx_insights_impacto ON insights(impacto);

-- Chat messages table
CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  function_call TEXT,
  function_result TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_messages_created_at ON chat_messages(created_at);
